version = 1
disable_existing_loggers = false

[formatters]
    [formatters.simple]
    format = "[%(asctime)s][%(levelname)-8s] %(name)s: %(message)s"
    datefmt = "%H:%M:%S"

    [formatters.verbose]
    format = "[%(asctime)s][%(levelname)-8s] %(name)s: %(message)s"
    datefmt = "%d/%m/%Y (%H:%M:%S)"

[handlers]
    [handlers.console]
    class = "logging.StreamHandler"
    formatter = "simple"
    level = "INFO"
    stream = "ext://sys.stdout"

    [handlers.console_discord]
    class = "logging.StreamHandler"
    formatter = "simple"
    level = "WARNING"
    stream = "ext://sys.stdout"

    [handlers.file]
    class = "logging.handlers.RotatingFileHandler"
    formatter = "verbose"
    level = "DEBUG"
    filename = "./logs/log.latest"
    encoding = "utf-8"
    maxBytes = 32_000_000
    backupCount = 5

[loggers.root]
    level = "DEBUG"
    handlers = ["console", "file"]

[loggers.discord]
    level = "INFO"
    handlers = ["file", "console_discord"]
    propagate = 0
